name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Configure SmartUI web static
        run: smartui config:web-static urls.json
      - name: xyz
       run: npm uninstall @lambdatest/smartui-cli ;npm i @lambdatest/smartui-cli
            
      - name: Create SmartUI web config
        run: smartui config:create-web smartui-web.json

      - name: Capture SmartUI
        run: smartui capture urls.json --config smartui-web.json
        env:
          SMARTUI_USER: ${{ secrets.LAMBDATEST_USERNAME }}
          SMARTUI_ACCESS_KEY: ${{ secrets.LAMBDATEST_ACCESS_KEY }}
